CREATE TABLE pessoa (
    id SERIAL PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    telefone VARCHAR(20) NOT NULL,
    data_nascimento DATE NOT NULL,
    cpf VARCHAR(14) NOT NULL UNIQUE
);

CREATE TABLE cliente (
    id SERIAL PRIMARY KEY,
    pessoa_id INTEGER NOT NULL,
    vip BOOLEAN NOT NULL DEFAULT FALSE,
    FOREIGN KEY (pessoa_id) REFERENCES pessoa(id)
);