-- drop table if exists SEXO;
CREATE TABLE IF NOT EXISTS SEXO (
    ID        SERIAL PRIMARY KEY, 
    DESCRICAO VARCHAR(20)
);

-- drop table if exists ENDERECO;
CREATE TABLE IF NOT EXISTS ENDERECO (
    ID     SERIAL PRIMARY KEY,
    RUA    VARCHAR(255),
    NUMERO VARCHAR(20),
    BAIRRO VARCHAR(100),
    CIDADE VARCHAR(100),
    ESTADO VARCHAR(50),
    CEP    VARCHAR(20)
);

-- drop table if exists CLASSE;
CREATE TABLE IF NOT EXISTS CLASSE (
    ID      SERIAL PRIMARY KEY,
    ESPECIE VARCHAR(255),
    RACA    VARCHAR(255)
);

-- drop table if exists PESSOA;
CREATE TABLE IF NOT EXISTS PESSOA (
    ID              SERIAL PRIMARY KEY,
    NOME            VARCHAR(80) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL,
    ID_SEXO         INT,
    EMAIL           VARCHAR(200) UNIQUE,
    CPF             BIGINT UNIQUE,
    TELEFONE        INTEGER,
    CONSTRAINT FK_SEXO_PESSOA FOREIGN KEY (ID_SEXO) REFERENCES SEXO (ID),
    CONSTRAINT CHK_IDADE_MINIMA CHECK (EXTRACT(YEAR FROM AGE(CURRENT_DATE, DATA_NASCIMENTO)) >= 16)
);

-- drop table if exists FUNCIONARIO;
CREATE TABLE IF NOT EXISTS FUNCIONARIO (
    ID            SERIAL PRIMARY KEY,
    ID_PESSOA     INTEGER NOT NULL,
    SALARIO       NUMERIC(10, 2),
    DATA_ADMISSAO DATE,
    CONSTRAINT FK_PESSOA_FUNCIONARIO FOREIGN KEY (ID_PESSOA) REFERENCES PESSOA (ID),
    CONSTRAINT CK_SALARIO_ATENDENTE  CHECK (SALARIO BETWEEN 2000 AND 40000)
);

-- drop table if exists ATENDENTE;
CREATE TABLE IF NOT EXISTS ATENDENTE (
    ID SERIAL PRIMARY KEY,
    ID_FUNCIONARIO INTEGER NOT NULL,
    QTD_ATENDIMENTOS INTEGER,
    CONSTRAINT FK_FUNCIONARIO_ATENDENTE FOREIGN KEY (ID_FUNCIONARIO) REFERENCES FUNCIONARIO (ID)
);

-- drop table if exists VETERINARIO;
CREATE TABLE IF NOT EXISTS VETERINARIO (
    ID SERIAL      PRIMARY KEY,
    ID_FUNCIONARIO INTEGER NOT NULL,
    ESPECIALIDADE  VARCHAR(255),
    CRMV VARCHAR(50),
    CONSTRAINT FK_FUNCIONARIO_VETERINARIO FOREIGN KEY (ID_FUNCIONARIO) REFERENCES FUNCIONARIO (ID)
);

-- drop table if exists CLIENTE;
CREATE TABLE IF NOT EXISTS CLIENTE (
    ID          SERIAL PRIMARY KEY,
    ID_PESSOA   INTEGER NOT NULL,
    ID_ENDERECO INTEGER,
    CONSTRAINT FK_CLIENTE_PESSOA   FOREIGN KEY (ID_PESSOA)   REFERENCES PESSOA (ID),
    CONSTRAINT FK_CLIENTE_ENDERECO FOREIGN KEY (ID_ENDERECO) REFERENCES ENDERECO (ID)
);

-- drop table if exists ANIMAL;
CREATE TABLE IF NOT EXISTS ANIMAL (
    ID SERIAL PRIMARY KEY,
    ID_SEXO INT,
    ID_CLASSE INT,
    ID_CLIENTE INTEGER NOT NULL,
    NOME VARCHAR(255),
    DATA_NASCIMENTO DATE,
    PESO NUMERIC(5, 2),
    CONSTRAINT FK_SEXO_ANIMAL FOREIGN KEY (ID_SEXO) REFERENCES SEXO (ID),
    CONSTRAINT FK_CLASSE_ANIMAL FOREIGN KEY (ID_CLASSE) REFERENCES CLASSE (ID),
    CONSTRAINT FK_ANIMAL_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID)
);

-- drop table if exists ATENDIMENTO;
CREATE TABLE IF NOT EXISTS ATENDIMENTO (
    ID SERIAL PRIMARY KEY,
    ID_ATENDENTE INTEGER NOT NULL,
    ID_VETERINARIO INTEGER NOT NULL,
    ID_ANIMAL INTEGER NOT NULL,
    TIPO_ATENDIMENTO VARCHAR(100),
    VALOR NUMERIC(10, 2),
    DATA_ATENDIMENTO DATE,
    TEXTO_CONSULTA TEXT,
    CONSTRAINT FK_ATENDIMENTO_VETERINARIO FOREIGN KEY (ID_VETERINARIO) REFERENCES VETERINARIO(ID),
    CONSTRAINT FK_ATENDIMENTO_ATENDENTE   FOREIGN KEY (ID_ATENDENTE)   REFERENCES ATENDENTE(ID),
    CONSTRAINT FK_ATENDIMENTO_ANIMAL      FOREIGN KEY (ID_ANIMAL)      REFERENCES ANIMAL(ID)
);

-- drop table if exists PEDIDO;
CREATE TABLE IF NOT EXISTS PEDIDO (
    ID          SERIAL PRIMARY KEY,
    ID_CLIENTE  INTEGER NOT NULL,
    DATA_PEDIDO  DATE,
    STATUS      VARCHAR(50),
    CONSTRAINT FK_PEDIDO_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(id)
);

-- drop table if exists PRODUTO;
CREATE TABLE IF NOT EXISTS PRODUTO (
    ID      SERIAL PRIMARY KEY,
    NOME    VARCHAR(255),
    MARCA   VARCHAR(255),
    PRECO   NUMERIC(10, 2),
    ESTOQUE INTEGER
);

-- drop table if exists PRODUTO_PEDIDO;
CREATE TABLE IF NOT EXISTS PRODUTO_PEDIDO (
    ID          SERIAL PRIMARY KEY,
    ID_PEDIDO   INTEGER NOT NULL,
    ID_PRODUTO  INTEGER NOT NULL,
    QUANTIDADE  INTEGER,
    VALOR_TOTAL NUMERIC(10, 2),
    PRIMARY KEY (ID_PEDIDO, ID_PRODUTO),
    CONSTRAINT FK_PP_PEDIDO  FOREIGN KEY (ID_PEDIDO)  REFERENCES PEDIDO(id),
    CONSTRAINT FK_PP_PRODUTO FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO(id)
);

CREATE TABLE IF NOT EXISTS NOTA_FISCAL (
    ID                SERIAL PRIMARY KEY,
    ID_PRODUTO_PEDIDO INTEGER NOT NULL,
    DATA_EMISSAO      DATE,
    NUMERO_SERIE      VARCHAR(50),
    CONSTRAINT FK_NF_PRODUTO_PEDIDO FOREIGN KEY (ID_PRODUTO_PEDIDO) REFERENCES PRODUTO_PEDIDO(ID)
);